<a href="https://colab.research.google.com/github/cmilanes93/Hackathon/blob/main/Pre_Pocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd 
import matplotlib.pyplot as plt
import seaborn as sns

# Leer dataset y hacer analisis

In [ ]:
df = pd.read_csv('https://raw.githubusercontent.com/ArielxX/hackathon-bbva-2022/main/dataset_tasacion_test_vf2.csv', encoding='latin-1')

In [ ]:
df

,ID,Fecha entrega del Informe,Tipo de vía,Piso,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),...,Categoría del bien,Posición,Número de frentes,Edad,Elevador,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
0,1,2021-05-21 00:00:00,1.0,NaN,Lima,Lima,Surquillo,0.0,0.0,-12.105644,...,Departamento,NaN,NaN,5.0,NaN,Bueno,Comparación de mercado (directo),13.72,63.92,138169
1,2,2017-11-26 00:00:00,1.0,NaN,Lima,Lima,Santiago de Surco,1.0,0.0,-12.138068,...,Departamento,NaN,NaN,4.0,NaN,Muy bueno,Comparación de mercado (directo),32.93,111.12,203712
2,3,2019-03-01 00:00:00,1.0,NaN,Lima,Lima,San Miguel,1.0,1.0,-12.076288,...,Oficina,NaN,NaN,5.0,NaN,Bueno,Comparación de mercado (directo),5.09,106.22,145911
3,4,2019-11-22 00:00:00,3.0,NaN,Ucayali,Coronel Portillo,Calleria,NaN,NaN,-8.381362,...,Terreno Urbano,NaN,NaN,NaN,NaN,NaN,Costos o reposición (directo),329.50,0.00,180275
4,5,2020-10-16 00:00:00,3.0,NaN,Lima,Lima,Magdalena del Mar,0.0,0.0,-12.091392,...,Oficina,NaN,NaN,0.0,NaN,En proyecto,Comparación de mercado (directo),3.16,57.77,105719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19354,19355,2019-06-11 00:00:00,NaN,NaN,Lima,Lima,Ate,NaN,NaN,-12.080748,...,Departamento,NaN,NaN,2.0,NaN,Bueno,Costos o reposición (directo),160.00,600.00,474880
19355,19356,2016-11-24 00:00:00,NaN,NaN,Tumbes,Tumbes,Tumbes,0.0,0.0,-3.557133,...,Vivienda Unifamiliar,NaN,NaN,6.0,NaN,NaN,Costos o reposición (directo),105.75,225.65,61713
19356,19357,2021-11-03 00:00:00,1.0,NaN,Lima,Lima,San Miguel,0.0,1.0,-12.081247,...,Departamento,NaN,NaN,1.0,NaN,En construcción,Comparación de mercado (directo),5.65,71.70,123510
19357,19358,2019-06-16 00:00:00,4.0,NaN,Lambayeque,Chiclayo,Chiclayo,0.0,0.0,-6.772513,...,Vivienda Unifamiliar,NaN,NaN,38.0,NaN,Regular,Costos o reposición (directo),162.00,89.59,99631
19358,19359,2019-07-14 00:00:00,1.0,NaN,Lima,Lima,Santiago de Surco,0.0,0.0,-12.102021,...,Departamento,NaN,NaN,0.0,NaN,En construcción,Comparación de mercado (directo),12.82,52.58,147769

In [ ]:
df.isna().sum()

ID                               0
Fecha entrega del Informe        0
Tipo de vía                   1842
Piso                         19341
Departamento                     0
Provincia                        0
Distrito                         0
Número de estacionamiento     2808
Depósitos                     2837
Latitud (Decimal)               41
Longitud (Decimal)              66
Categoría del bien               0
Posición                     19313
Número de frentes            19315
Edad                          1527
Elevador                     19311
Estado de conservación        5227
Método Representado              1
Área Terreno                    18
Área Construcción             1322
Valor comercial (USD)            0
dtype: int64

In [ ]:
df = df.drop(columns=['Piso', 'Posición', 'Número de frentes', 'Elevador'])

In [ ]:
df

,ID,Fecha entrega del Informe,Tipo de vía,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Edad,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
0,1,2021-05-21 00:00:00,1.0,Lima,Lima,Surquillo,0.0,0.0,-12.105644,-77.025705,Departamento,5.0,Bueno,Comparación de mercado (directo),13.72,63.92,138169
1,2,2017-11-26 00:00:00,1.0,Lima,Lima,Santiago de Surco,1.0,0.0,-12.138068,-76.985660,Departamento,4.0,Muy bueno,Comparación de mercado (directo),32.93,111.12,203712
2,3,2019-03-01 00:00:00,1.0,Lima,Lima,San Miguel,1.0,1.0,-12.076288,-77.090878,Oficina,5.0,Bueno,Comparación de mercado (directo),5.09,106.22,145911
3,4,2019-11-22 00:00:00,3.0,Ucayali,Coronel Portillo,Calleria,NaN,NaN,-8.381362,-74.537930,Terreno Urbano,NaN,NaN,Costos o reposición (directo),329.50,0.00,180275
4,5,2020-10-16 00:00:00,3.0,Lima,Lima,Magdalena del Mar,0.0,0.0,-12.091392,-77.055850,Oficina,0.0,En proyecto,Comparación de mercado (directo),3.16,57.77,105719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19354,19355,2019-06-11 00:00:00,NaN,Lima,Lima,Ate,NaN,NaN,-12.080748,-76.984533,Departamento,2.0,Bueno,Costos o reposición (directo),160.00,600.00,474880
19355,19356,2016-11-24 00:00:00,NaN,Tumbes,Tumbes,Tumbes,0.0,0.0,-3.557133,-80.442444,Vivienda Unifamiliar,6.0,NaN,Costos o reposición (directo),105.75,225.65,61713
19356,19357,2021-11-03 00:00:00,1.0,Lima,Lima,San Miguel,0.0,1.0,-12.081247,-77.093158,Departamento,1.0,En construcción,Comparación de mercado (directo),5.65,71.70,123510
19357,19358,2019-06-16 00:00:00,4.0,Lambayeque,Chiclayo,Chiclayo,0.0,0.0,-6.772513,-79.861140,Vivienda Unifamiliar,38.0,Regular,Costos o reposición (directo),162.00,89.59,99631
19358,19359,2019-07-14 00:00:00,1.0,Lima,Lima,Santiago de Surco,0.0,0.0,-12.102021,-76.965712,Departamento,0.0,En construcción,Comparación de mercado (directo),12.82,52.58,147769

In [ ]:
df.isna().sum()

ID                              0
Fecha entrega del Informe       0
Tipo de vía                  1842
Departamento                    0
Provincia                       0
Distrito                        0
Número de estacionamiento    2808
Depósitos                    2837
Latitud (Decimal)              41
Longitud (Decimal)             66
Categoría del bien              0
Edad                         1527
Estado de conservación       5227
Método Representado             1
Área Terreno                   18
Área Construcción            1322
Valor comercial (USD)           0
dtype: int64

# TODO

TODO:

1 - Imputar ✅

2 - Nuevas categorias del bien ✅

3 - Orden a estado de conservacion ✅

4 - Mapear categorias (guardar json con valores del diccionario)

5 - Guardar los 4 csv:
* quitar provincia y dept
* quitar provincia, dept y areas
* quitar provincia y distrito
* quitar provincia, distrito y areas

6 - Entrenar modelos y guardarlos

7 - Hostear (aws)

Modelos:

Fijando Lima como provincia (olvidando departamento) con area/ sin area

Con todos los departamentos sin distritos ni provincia con area / sin area

Imputar:

Tipo de vía                   0.0

Número de estacionamiento     0

Depósitos                     0

Latitud (Decimal)             Calcular por distrito

Longitud (Decimal)            Calcular por distrito

Categoría del bien            Unir categorias / imputar con 0

Edad                          Media

Estado de conservación        Darle orden / imputar en 0

Método Representado           0

Área Terreno                  imputar con otra area

Área Construcción             imputar con otra area

In [ ]:
cat_column = ['Tipo de vía', 'Departamento', 'Provincia', 'Distrito', 'Categoría del bien', 'Estado de conservación', 'Método Representado']

for col in cat_column:
    print(col + ':')
    print(df[col].value_counts())
    print()

Tipo de vía:
1.0     8036
3.0     4876
2.0     3737
4.0      464
5.0      381
9.0       18
7.0        3
6.0        1
10.0       1
Name: Tipo de vía, dtype: int64

Departamento:
Lima             13420
La Libertad        787
Arequipa           644
Piura              504
Lambayeque         479
Junín              473
San Martín         445
Huancavelica       441
Callao             394
Loreto             383
Áncash             282
Cusco              254
Ucayali            218
Huánuco            157
Cajamarca          132
Tacna               88
Puno                67
Pasco               51
Tumbes              50
Ayacucho            46
Apurímac            22
Moquegua            11
Madre de Dios        6
Amazonas             5
Name: Departamento, dtype: int64

Provincia:
Lima                       12828
Trujillo                     694
Arequipa                     619
Chiclayo                     425
Prov. Const. del Callao      394
                           ...
Camaná                         1
Tayacaja                       1
Bagua                          1
Jauja                          1
Huari                          1
Name: Provincia, Length: 113, dtype: int64

Distrito:
Santiago de Surco    1824
Miraflores            991
Lima                  680
La Molina             666
San Borja             652
                     ...
Colan                   1
Mito                    1
Salitral                1
Ramón Castilla          1
Matahuasi               1
Name: Distrito, Length: 351, dtype: int64

Categoría del bien:
Departamento            9483
Vivienda Unifamiliar    4835
Local Comercial         2311
Terreno Urbano          2221
Oficina                  509
Name: Categoría del bien, dtype: int64

Estado de conservación:
Bueno              8397
Regular            2146
Muy bueno          1511
En construcción    1453
En proyecto         512
Malo                113
Name: Estado de conservación, dtype: int64

Método Representado:
Comparación de mercado (directo)      11631
Costos o reposición (directo)          7707
Renta o capitalización (indirecto)       20
Name: Método Representado, dtype: int64

# Imputaciones

In [ ]:
### Valores llenados con cero
df['Tipo de vía'].fillna(0, inplace=True)
df['Número de estacionamiento'].fillna(0, inplace=True)
df['Depósitos'].fillna(0, inplace=True)
df['Método Representado'].fillna(0, inplace=True)
df['Área Terreno'].fillna(0, inplace=True)
df['Área Construcción'].fillna(0, inplace=True)
df['Estado de conservación'].fillna(0, inplace=True)

In [ ]:
###Valores de la media
df['Edad'].fillna(df['Edad'].mean(), inplace=True)

In [ ]:
Map = {}

In [ ]:
from numpy import nan

### Darle orden a Estado de conservación
dct = {
    0 : 0,
    'Malo': 1,
    'Regular - Malo' : 2,
    'En proyecto' : 3,
    'En construcción' : 4,
    'Regular' : 5,
    'Bueno - Regular' : 6,
    'Bueno' : 7,
    'Muy bueno' : 8
}

Map['Estado de conservación'] = dct

df['Estado de conservación'] = df['Estado de conservación'].map(dct)

In [ ]:
df

,ID,Fecha entrega del Informe,Tipo de vía,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Edad,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
0,1,2021-05-21 00:00:00,1.0,Lima,Lima,Surquillo,0.0,0.0,-12.105644,-77.025705,Departamento,5.000000,7,Comparación de mercado (directo),13.72,63.92,138169
1,2,2017-11-26 00:00:00,1.0,Lima,Lima,Santiago de Surco,1.0,0.0,-12.138068,-76.985660,Departamento,4.000000,8,Comparación de mercado (directo),32.93,111.12,203712
2,3,2019-03-01 00:00:00,1.0,Lima,Lima,San Miguel,1.0,1.0,-12.076288,-77.090878,Oficina,5.000000,7,Comparación de mercado (directo),5.09,106.22,145911
3,4,2019-11-22 00:00:00,3.0,Ucayali,Coronel Portillo,Calleria,0.0,0.0,-8.381362,-74.537930,Terreno Urbano,16.132739,0,Costos o reposición (directo),329.50,0.00,180275
4,5,2020-10-16 00:00:00,3.0,Lima,Lima,Magdalena del Mar,0.0,0.0,-12.091392,-77.055850,Oficina,0.000000,3,Comparación de mercado (directo),3.16,57.77,105719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19354,19355,2019-06-11 00:00:00,0.0,Lima,Lima,Ate,0.0,0.0,-12.080748,-76.984533,Departamento,2.000000,7,Costos o reposición (directo),160.00,600.00,474880
19355,19356,2016-11-24 00:00:00,0.0,Tumbes,Tumbes,Tumbes,0.0,0.0,-3.557133,-80.442444,Vivienda Unifamiliar,6.000000,0,Costos o reposición (directo),105.75,225.65,61713
19356,19357,2021-11-03 00:00:00,1.0,Lima,Lima,San Miguel,0.0,1.0,-12.081247,-77.093158,Departamento,1.000000,4,Comparación de mercado (directo),5.65,71.70,123510
19357,19358,2019-06-16 00:00:00,4.0,Lambayeque,Chiclayo,Chiclayo,0.0,0.0,-6.772513,-79.861140,Vivienda Unifamiliar,38.000000,5,Costos o reposición (directo),162.00,89.59,99631
19358,19359,2019-07-14 00:00:00,1.0,Lima,Lima,Santiago de Surco,0.0,0.0,-12.102021,-76.965712,Departamento,0.000000,4,Comparación de mercado (directo),12.82,52.58,147769

In [ ]:
### Calcular representacion de lat y lng por distrito

df['Latitud (Decimal)'].fillna(0, inplace=True)
df['Longitud (Decimal)'].fillna(0, inplace=True)

Distritos = df['Distrito'].unique()

dstr_lat = {}
dstr_lng = {}
amm_lat = {}
amm_lng = {}

for d in Distritos:
    dstr_lat[d] = 0.0
    dstr_lng[d] = 0.0
    amm_lat[d] = 0
    amm_lng[d] = 0

for index, row in df.iterrows():
    d = row['Distrito']
    if row['Latitud (Decimal)'] != 0:
        amm_lat[d] += 1
        dstr_lat[d] += row['Latitud (Decimal)']
    
    if row['Longitud (Decimal)'] != 0:
        amm_lng[d] += 1
        dstr_lng[d] += row['Longitud (Decimal)']

In [ ]:
for d in Distritos:
    dstr_lat[d] /= amm_lat[d]
    dstr_lng[d] /= amm_lng[d]

In [ ]:
for index, row in df.iterrows():
    d = row['Distrito']
    if row['Latitud (Decimal)'] == 0:
        df.at[index,'Latitud (Decimal)'] = dstr_lat[d]
    
    if row['Longitud (Decimal)'] == 0:
        df.at[index,'Longitud (Decimal)'] = dstr_lng[d]

In [ ]:
Map['Latitud'] = dstr_lat
Map['Longitud'] = dstr_lng

In [ ]:
### Mapear categoria del bien

# 0 nan
# 1 Vivienda unifamiliar = Departamento + Vivienda Unifamiliar
# 2 Terrenos = Terreno Urbano + Terreno Rústico (eriazo)
# 3 Industria = Industria + Almacén /Taller + Fundo Agrícola + Muebles y enseres + Maquinaria y/o Equipo
# 4 Negocios= Local Comercial + Oficina + Hotel
# 5 Servicios = Centro de Salud + Intitución Educativa
# 6 AVALUOS_TIPOS_INMUEBLE_VEHICULO
# 7 Estacionamiento/depósito (U.I.) 

df['Categoría del bien'].fillna(0, inplace=True)

cats = {
    0: 0,
    'Departamento' : 1,
    'Vivienda Unifamiliar' : 1,
    'Terreno Urbano' : 2,
    'Terreno Rústico (eriazo)' : 2,
    'Industria' : 3,
    'Almacén /Taller' : 3,
    'Fundo Agrícola' : 3,
    'Muebles y enseres' : 3,
    'Maquinaria y/o Equipo' : 3,
    'Local Comercial' : 4,
    'Oficina' : 4,
    'Hotel' : 4,
    'Centro de Salud' : 5,
    'Intitución Educativa' : 5,
    'AVALUOS_TIPOS_INMUEBLE_VEHICULO' : 6,
    'Estacionamiento/depósito (U.I.)' : 7
}

Map['Categoría del bien'] = cats

In [ ]:
df['Categoría del bien'] = df['Categoría del bien'].map(cats)

# Mapear categorias

In [ ]:
### Mapear Distritos

distr = df['Distrito'].unique()

dst = {}

i = 1

for d in distr:
    dst[d] = i
    i += 1

Map['Distrito'] = dst

df['Distrito'] = df['Distrito'].map(dst)

In [ ]:
### Mapear Departamentos

deptmnt = df['Departamento'].unique()

dpto = {}

i = 1

for d in deptmnt:
    dpto[d] = i
    i += 1

Map['Departamento'] = dpto

df['Departamento'] = df['Departamento'].map(dpto)

In [ ]:
### Mapear Método Representados

metodos = df['Método Representado'].unique()

mtd = {}

i = 1

for d in metodos:
    mtd[d] = i
    i += 1

Map['Método Representado'] = mtd

df['Método Representado'] = df['Método Representado'].map(mtd)

In [ ]:
# Cambiar fecha por año

for index, row in df.iterrows():
    fecha = row['Fecha entrega del Informe']
    df.at[index,'Fecha entrega del Informe'] = int(fecha[:4])

In [ ]:
df

,ID,Fecha entrega del Informe,Tipo de vía,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Edad,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
0,1,2021,1.0,1,Lima,1,0.0,0.0,-12.105644,-77.025705,1,5.000000,7,1,13.72,63.92,138169
1,2,2017,1.0,1,Lima,2,1.0,0.0,-12.138068,-76.985660,1,4.000000,8,1,32.93,111.12,203712
2,3,2019,1.0,1,Lima,3,1.0,1.0,-12.076288,-77.090878,4,5.000000,7,1,5.09,106.22,145911
3,4,2019,3.0,2,Coronel Portillo,4,0.0,0.0,-8.381362,-74.537930,2,16.132739,0,2,329.50,0.00,180275
4,5,2020,3.0,1,Lima,5,0.0,0.0,-12.091392,-77.055850,4,0.000000,3,1,3.16,57.77,105719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19354,19355,2019,0.0,1,Lima,24,0.0,0.0,-12.080748,-76.984533,1,2.000000,7,2,160.00,600.00,474880
19355,19356,2016,0.0,17,Tumbes,58,0.0,0.0,-3.557133,-80.442444,1,6.000000,0,2,105.75,225.65,61713
19356,19357,2021,1.0,1,Lima,3,0.0,1.0,-12.081247,-77.093158,1,1.000000,4,1,5.65,71.70,123510
19357,19358,2019,4.0,16,Chiclayo,48,0.0,0.0,-6.772513,-79.861140,1,38.000000,5,2,162.00,89.59,99631
19358,19359,2019,1.0,1,Lima,2,0.0,0.0,-12.102021,-76.965712,1,0.000000,4,1,12.82,52.58,147769

In [ ]:
for index, row in df.iterrows():
    if row['Área Terreno'] == 0:
        df.at[index,'Área Terreno'] = row['Área Construcción']

    if row['Área Construcción'] == 0:
        df.at[index,'Área Construcción'] = row['Área Terreno']

In [ ]:
df.isna().sum()

ID                           0
Fecha entrega del Informe    0
Tipo de vía                  0
Departamento                 0
Provincia                    0
Distrito                     0
Número de estacionamiento    0
Depósitos                    0
Latitud (Decimal)            0
Longitud (Decimal)           0
Categoría del bien           0
Edad                         0
Estado de conservación       0
Método Representado          0
Área Terreno                 0
Área Construcción            0
Valor comercial (USD)        0
dtype: int64

In [ ]:
df_with_areas = df.copy()
df_no_areas = df.copy()

df_no_areas = df_no_areas.drop(columns=['Área Terreno', 'Área Construcción'])

In [ ]:
##Filtrar area mayores a 5
df_with_areas = df_with_areas.loc[df['Área Terreno'] >= 5]

In [ ]:
df_with_areas

,ID,Fecha entrega del Informe,Tipo de vía,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Edad,Estado de conservación,Método Representado,Área Terreno,Área Construcción,Valor comercial (USD)
0,1,2021,1.0,1,Lima,1,0.0,0.0,-12.105644,-77.025705,1,5.000000,7,1,13.72,63.92,138169
1,2,2017,1.0,1,Lima,2,1.0,0.0,-12.138068,-76.985660,1,4.000000,8,1,32.93,111.12,203712
2,3,2019,1.0,1,Lima,3,1.0,1.0,-12.076288,-77.090878,4,5.000000,7,1,5.09,106.22,145911
3,4,2019,3.0,2,Coronel Portillo,4,0.0,0.0,-8.381362,-74.537930,2,16.132739,0,2,329.50,329.50,180275
4,5,2020,3.0,1,Lima,5,0.0,0.0,-12.091392,-77.055850,4,0.000000,3,1,3.16,57.77,105719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19354,19355,2019,0.0,1,Lima,24,0.0,0.0,-12.080748,-76.984533,1,2.000000,7,2,160.00,600.00,474880
19355,19356,2016,0.0,17,Tumbes,58,0.0,0.0,-3.557133,-80.442444,1,6.000000,0,2,105.75,225.65,61713
19356,19357,2021,1.0,1,Lima,3,0.0,1.0,-12.081247,-77.093158,1,1.000000,4,1,5.65,71.70,123510
19357,19358,2019,4.0,16,Chiclayo,48,0.0,0.0,-6.772513,-79.861140,1,38.000000,5,2,162.00,89.59,99631
19358,19359,2019,1.0,1,Lima,2,0.0,0.0,-12.102021,-76.965712,1,0.000000,4,1,12.82,52.58,147769

In [ ]:
df_no_areas

,ID,Fecha entrega del Informe,Tipo de vía,Departamento,Provincia,Distrito,Número de estacionamiento,Depósitos,Latitud (Decimal),Longitud (Decimal),Categoría del bien,Edad,Estado de conservación,Método Representado,Valor comercial (USD)
0,1,2021,1.0,1,Lima,1,0.0,0.0,-12.105644,-77.025705,1,5.000000,7,1,138169
1,2,2017,1.0,1,Lima,2,1.0,0.0,-12.138068,-76.985660,1,4.000000,8,1,203712
2,3,2019,1.0,1,Lima,3,1.0,1.0,-12.076288,-77.090878,4,5.000000,7,1,145911
3,4,2019,3.0,2,Coronel Portillo,4,0.0,0.0,-8.381362,-74.537930,2,16.132739,0,2,180275
4,5,2020,3.0,1,Lima,5,0.0,0.0,-12.091392,-77.055850,4,0.000000,3,1,105719
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19354,19355,2019,0.0,1,Lima,24,0.0,0.0,-12.080748,-76.984533,1,2.000000,7,2,474880
19355,19356,2016,0.0,17,Tumbes,58,0.0,0.0,-3.557133,-80.442444,1,6.000000,0,2,61713
19356,19357,2021,1.0,1,Lima,3,0.0,1.0,-12.081247,-77.093158,1,1.000000,4,1,123510
19357,19358,2019,4.0,16,Chiclayo,48,0.0,0.0,-6.772513,-79.861140,1,38.000000,5,2,99631
19358,19359,2019,1.0,1,Lima,2,0.0,0.0,-12.102021,-76.965712,1,0.000000,4,1,147769

In [ ]:
# Datasets de Lima

df_Lima_with_areas = df_with_areas.loc[df['Provincia'] == 'Lima'].drop(columns=['Provincia', 'Departamento'])
df_Lima_no_areas = df_no_areas.loc[df['Provincia'] == 'Lima'].drop(columns=['Provincia', 'Departamento'])

In [ ]:
df_Lima_with_areas.to_csv('Lima_with_areas.csv', index=False)

In [ ]:
df_Lima_no_areas.to_csv('Lima_no_areas.csv', index=False)

In [ ]:
# Datasets de Departamentos

df_Dto_with_areas = df_with_areas.drop(columns=['Provincia', 'Distrito'])
df_Dto_no_areas = df_no_areas.drop(columns=['Provincia', 'Distrito'])

In [ ]:
df_Dto_with_areas.to_csv('Dto_with_areas.csv', index=False)

In [ ]:
df_Dto_no_areas.to_csv('Dto_no_areas.csv', index=False)